### PR TITLE
added 3 new experiments for kubernetes

### PR DESCRIPTION
**Pull request by navinjoy**

### CODE REVIEW

**Comment by navinjoy** [comment]
I am not able to add the reviewers... @sumitnagal @ksatchit can you please review this.

**Comment by sumitnagal** [comment]
@navinjoy , please remove active monitor from these charts. Also, you have not added workflow, please add that too.

**Comment by ksatchit** [comment]
@navinjoy can you place the alb related manifests under kube-aws chart

**Comment by sumitnagal** [comment]
alb ingress is kubernetes way .. not the aws specific hence we moved in k8.

**Review by sumitnagal — APPROVED** [review]
LGTM

**Pull request merged**
