### PR TITLE
update(images): update image tags to 1.4.1

### PR DESCRIPTION
**Pull request by ispeakc0de**
Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

### CODE REVIEW

**Comment by ksatchit** [comment]
@ispeakc0de any other changes we need to pick into this PR? or cherry picks

**Comment by ispeakc0de** [comment]
> @ispeakc0de any other changes we need to pick into this PR? or cherry picks

No, All are up to date already

**Review by uditgaurav — APPROVED** [review]

**Comment by uditgaurav** [comment]
@ksatchit lib litmus PR is approved but not merged. Should we take that also?
https://github.com/litmuschaos/chaos-charts/pull/233
cc: @ispeakc0de

**Comment by ksatchit** [comment]
> @ksatchit lib litmus PR is approved but not merged. Should we take that also?

I guess we can do it for all the exp which need litmus in there but are not present.

**Review by ksatchit — APPROVED** [review]

**Review by uditgaurav — APPROVED** [review]

**Pull request merged**
