### PR TITLE
node-memory-hog.png

### PR DESCRIPTION
**Pull request by aniketrathi1999**
memory hog

### CODE REVIEW

**Comment by aniketrathi1999** [comment]
Pod memory hog

**Comment by aniketrathi1999** [comment]
kubelet kill

**Comment by ajeshbaby** [comment]
Only one file has been raised.. Can you put all three files in this PR also update the description and heading as new icons for chartsts ..

**Comment by ajeshbaby** [comment]
Closing this #246 address the same.

**Pull request closed without merging**
