### PR TITLE
(refactor): update the pumba image

### PR DESCRIPTION
**Pull request by ksatchit**
- Update the pumba images to 0.6.5
- Refer: https://github.com/litmuschaos/litmus/pull/991

Signed-off-by: ksatchit <ksatchit@mayadata.io>

### CODE REVIEW

**Comment by rahulchheda** [comment]
Were the experiments, updated to use this pumba image, talking about the changes required to support this image in the experiments. @ksatchit

**Review by ajeshbaby — APPROVED** [review]
LGTM

**Comment by ksatchit** [comment]
> Were the experiments, updated to use this pumba image, talking about the changes required to support this image in the experiments. @ksatchit

Yes @rahulchheda , have referenced the litmuschaos/litmus chaoslib changes in the PR description

**Review by ispeakc0de — APPROVED** [review]
lgtm

**Comment by LaumiH** [comment]
Please merge this as soon as possible, otherwise the default config of experiments with netem will not work, the LIB_IMAGE has to be specified to pumba:latest until then ... !

**Comment by ksatchit** [comment]
> Please merge this as soon as possible, otherwise the default config of experiments with netem will not work, the LIB_IMAGE has to be specified to pumba:latest until then ... !

Done!

**Pull request merged**
