### PR TITLE
Added Workflows with Cron-Syntax for using in Litmus-portal.

### PR DESCRIPTION
**Pull request by Jonsy13**
**This PR will -**

**- Add Workflows with cron-Syntax.**

_**By default every worklfow is having Cron-Syntax for scheduling it every 1 hour.**_

### CODE REVIEW

**Review by ishangupta-ds — APPROVED** [review]
LGTM.

**Comment by ishangupta-ds** [comment]
can we delete the `cron-workflows` folder from root if we are planning to keep them inside each workflow in this way @ksatchit cc: @ajeshbaby

**Comment by ajeshbaby** [comment]
> can we delete the `cron-workflows` folder from the root if we are planning to keep them inside each workflow in this way @ksatchit cc: @ajeshbaby

Yes it can be deleted or along with the below cleanup.

Post-release of 1.9
- rename workflow.yaml to workflow_once.yaml

**Comment by ishangupta-ds** [comment]
> > can we delete the `cron-workflows` folder from the root if we are planning to keep them inside each workflow in this way @ksatchit cc: @ajeshbaby
> 
> Yes it can be deleted or along with the below cleanup.
> 
> Post-release of 1.9
> 
> * rename workflow.yaml to workflow_once.yaml

cc: @Jonsy13 @amityt @ksatchit

**Review by ksatchit — APPROVED** [review]

**Review by ajeshbaby — APPROVED** [review]
LGTM

**Pull request merged**
